package com.dt.cms.domain.sys;

import com.dt.cms.domain.BaseDomain;

public class Organization extends BaseDomain<Organization> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.org_name
	 *
	 * @mbggenerated
	 */
	private String orgName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.pid
	 *
	 * @mbggenerated
	 */
	private Integer pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.org_type
	 *
	 * @mbggenerated
	 */
	private String orgType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.org_sort
	 *
	 * @mbggenerated
	 */
	private Integer orgSort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.org_level
	 *
	 * @mbggenerated
	 */
	private Integer orgLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.org_code
	 *
	 * @mbggenerated
	 */
	private String orgCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column organization.area_id
	 *
	 * @mbggenerated
	 */
	private Integer areaId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.id
	 *
	 * @return the value of organization.id
	 *
	 * @mbggenerated
	 */

	public Organization() {

	}

	public Organization(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.id
	 *
	 * @param id
	 *            the value for organization.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.org_name
	 *
	 * @return the value of organization.org_name
	 *
	 * @mbggenerated
	 */
	public String getOrgName() {
		return orgName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.org_name
	 *
	 * @param orgName
	 *            the value for organization.org_name
	 *
	 * @mbggenerated
	 */
	public void setOrgName(String orgName) {
		this.orgName = orgName == null ? null : orgName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.pid
	 *
	 * @return the value of organization.pid
	 *
	 * @mbggenerated
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.pid
	 *
	 * @param pid
	 *            the value for organization.pid
	 *
	 * @mbggenerated
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.org_type
	 *
	 * @return the value of organization.org_type
	 *
	 * @mbggenerated
	 */
	public String getOrgType() {
		return orgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.org_type
	 *
	 * @param orgType
	 *            the value for organization.org_type
	 *
	 * @mbggenerated
	 */
	public void setOrgType(String orgType) {
		this.orgType = orgType == null ? null : orgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.org_sort
	 *
	 * @return the value of organization.org_sort
	 *
	 * @mbggenerated
	 */
	public Integer getOrgSort() {
		return orgSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.org_sort
	 *
	 * @param orgSort
	 *            the value for organization.org_sort
	 *
	 * @mbggenerated
	 */
	public void setOrgSort(Integer orgSort) {
		this.orgSort = orgSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.org_level
	 *
	 * @return the value of organization.org_level
	 *
	 * @mbggenerated
	 */
	public Integer getOrgLevel() {
		return orgLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.org_level
	 *
	 * @param orgLevel
	 *            the value for organization.org_level
	 *
	 * @mbggenerated
	 */
	public void setOrgLevel(Integer orgLevel) {
		this.orgLevel = orgLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.org_code
	 *
	 * @return the value of organization.org_code
	 *
	 * @mbggenerated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.org_code
	 *
	 * @param orgCode
	 *            the value for organization.org_code
	 *
	 * @mbggenerated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode == null ? null : orgCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column organization.area_id
	 *
	 * @return the value of organization.area_id
	 *
	 * @mbggenerated
	 */
	public Integer getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column organization.area_id
	 *
	 * @param areaId
	 *            the value for organization.area_id
	 *
	 * @mbggenerated
	 */
	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}
}